/**
 * 编辑器表情数据。
 *
 * - EMOJI_GROUPS:标准 unicode emoji,纯数据,无需任何资源,点击直接插入 emoji 字符。
 * - STICKERS:内置表情包(sticker),素材放在 client/public/stickers/,Twemoji SVG(Apache-2.0 / CC-BY-4.0)。
 *   插入时拼成 Markdown 图片 `![名称](/stickers/xxx.svg)`,与现有图片链路一致(相对路径,渲染走同源)。
 */

export interface EmojiGroup {
  name: string
  emojis: string[]
}

export interface Sticker {
  /** 展示名(alt) */
  name: string
  /** public/stickers 下的文件名 */
  file: string
}

/** 标准 Emoji(按常用分组,控制在 200 个以内避免面板过长) */
export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: '笑脸',
    emojis: [
      '😀', '😁', '😂', '🤣', '😊', '😇', '🙂', '😉', '😍', '😘', '😋', '😜',
      '🤪', '🤔', '🤨', '😐', '😑', '😶', '😏', '😒', '🙄', '😬', '😌', '😔',
      '😪', '🤤', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🥵', '🥶', '😎', '🤓',
      '🥳', '😭', '😤', '😠', '😡', '🤬', '🤯', '😱', '😨', '😰', '😥', '😓',
      '🤗', '🤭', '🤫', '😳', '😞', '😟', '😢', '😣', '😖', '😫', '😩', '🥺',
      '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '🤖', '😺',
    ],
  },
  {
    name: '手势',
    emojis: [
      '👍', '👎', '👌', '🤌', '✌️', '🤞', '🤟', '🤘', '🤙', '👈', '👉', '👆',
      '👇', '☝️', '✋', '🤚', '🖐️', '🖖', '👋', '🤝', '🙏', '✍️', '💪', '🦾',
      '👀', '👁️', '👃', '👂', '🦻', '👄', '🦷', '👅',
    ],
  },
  {
    name: '爱心',
    emojis: [
      '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕',
      '💞', '💓', '💗', '💖', '💘', '💝', '💟', '♥️', '💌', '💋', '💍', '💎',
    ],
  },
  {
    name: '符号',
    emojis: [
      '✅', '❌', '⭕', '💯', '🔥', '⭐', '🌟', '✨', '⚡', '💫', '💥', '💢',
      '💦', '💨', '💬', '👥', '💭', '🎉', '🎊', '🎁', '🎈', '🎏', '🎀', '🥰',
    ],
  },
]

/** 内置表情包清单(文件名 → 中文名),与 public/stickers/ 目录一一对应 */
export const STICKERS: Sticker[] = [
  { name: '点赞', file: 'zan.svg' },
  { name: '着火', file: 'huo.svg' },
  { name: '满分', file: '100.svg' },
  { name: '庆祝', file: 'pa.svg' },
  { name: '大笑', file: 'xiao.svg' },
  { name: '大哭', file: 'ku.svg' },
  { name: '爱心', file: 'ai.svg' },
  { name: '流汗', file: 'han.svg' },
  { name: '好的', file: 'ok.svg' },
  { name: '祈祷', file: 'qidao.svg' },
  { name: '肌肉', file: 'shoulibing.svg' },
  { name: '鼓掌', file: 'guzhang.svg' },
  { name: '敬礼', file: 'jingli.svg' },
  { name: '比心', file: 'bixin.svg' },
  { name: '老板打赏', file: 'laoyedashang.svg' },
  { name: '火箭', file: 'huojian.svg' },
  { name: '举手', file: 'jushou.svg' },
  { name: '耶', file: 'v.svg' },
  { name: '思考', file: 'sikao.svg' },
  { name: '眨眼', file: 'zhayan.svg' },
  { name: '邪笑', file: 'xiexiao.svg' },
  { name: '海笑', file: 'haixiao.svg' },
  { name: '生气', file: 'shengqi.svg' },
  { name: '困', file: 'kun.svg' },
  { name: '尴尬', file: 'gan.svg' },
  { name: '小丑', file: 'xiaochou.svg' },
  { name: '感觉', file: 'ganjue.svg' },
  { name: '狗屎', file: 'goushi.svg' },
  { name: '鬼把', file: 'guiba.svg' },
  { name: '外星人', file: 'waixingren.svg' },
  { name: '机器人', file: 'jiqiren.svg' },
  { name: '小狗', file: 'gou.svg' },
  { name: '小猫', file: 'mao.svg' },
  { name: '熊猫', file: 'xiongmao.svg' },
  { name: '狐狸', file: 'huli.svg' },
  { name: '猴子', file: 'houzi.svg' },
  { name: '小猪', file: 'zhu.svg' },
  { name: '青蛙', file: 'qingwa.svg' },
  { name: '蜜蜂', file: 'mifeng.svg' },
  { name: '虫子', file: 'chong.svg' },
  { name: '小鸡', file: 'ji.svg' },
  { name: '企鹅', file: 'qi_e.svg' },
  { name: '小鱼', file: 'yu.svg' },
  { name: '海豚', file: 'haitun.svg' },
  { name: '老虎', file: 'hu.svg' },
  { name: '考拉', file: 'kaola.svg' },
  { name: '独角兽', file: 'dujiaoshou.svg' },
  // ── NodeLoc 收编表情包(2026-09-02):ac 系列 54 + 小黄鸡 xhj 系列 49,png/gif/jpeg 混合 ──
  { name: 'ac01', file: 'ac01.png' },
  { name: 'ac02', file: 'ac02.png' },
  { name: 'ac03', file: 'ac03.png' },
  { name: 'ac04', file: 'ac04.png' },
  { name: 'ac05', file: 'ac05.png' },
  { name: 'ac06', file: 'ac06.png' },
  { name: 'ac07', file: 'ac07.png' },
  { name: 'ac08', file: 'ac08.png' },
  { name: 'ac09', file: 'ac09.png' },
  { name: 'ac10', file: 'ac10.png' },
  { name: 'ac11', file: 'ac11.png' },
  { name: 'ac12', file: 'ac12.png' },
  { name: 'ac13', file: 'ac13.png' },
  { name: 'ac14', file: 'ac14.png' },
  { name: 'ac15', file: 'ac15.png' },
  { name: 'ac16', file: 'ac16.png' },
  { name: 'ac17', file: 'ac17.png' },
  { name: 'ac18', file: 'ac18.png' },
  { name: 'ac19', file: 'ac19.png' },
  { name: 'ac20', file: 'ac20.png' },
  { name: 'ac21', file: 'ac21.png' },
  { name: 'ac22', file: 'ac22.png' },
  { name: 'ac23', file: 'ac23.png' },
  { name: 'ac24', file: 'ac24.png' },
  { name: 'ac25', file: 'ac25.png' },
  { name: 'ac26', file: 'ac26.png' },
  { name: 'ac27', file: 'ac27.png' },
  { name: 'ac28', file: 'ac28.png' },
  { name: 'ac29', file: 'ac29.png' },
  { name: 'ac30', file: 'ac30.png' },
  { name: 'ac31', file: 'ac31.png' },
  { name: 'ac32', file: 'ac32.png' },
  { name: 'ac33', file: 'ac33.png' },
  { name: 'ac34', file: 'ac34.png' },
  { name: 'ac35', file: 'ac35.png' },
  { name: 'ac36', file: 'ac36.png' },
  { name: 'ac37', file: 'ac37.png' },
  { name: 'ac38', file: 'ac38.png' },
  { name: 'ac39', file: 'ac39.png' },
  { name: 'ac40', file: 'ac40.png' },
  { name: 'ac41', file: 'ac41.png' },
  { name: 'ac42', file: 'ac42.png' },
  { name: 'ac43', file: 'ac43.png' },
  { name: 'ac44', file: 'ac44.png' },
  { name: 'ac45', file: 'ac45.png' },
  { name: 'ac46', file: 'ac46.png' },
  { name: 'ac47', file: 'ac47.png' },
  { name: 'ac48', file: 'ac48.png' },
  { name: 'ac49', file: 'ac49.png' },
  { name: 'ac50', file: 'ac50.png' },
  { name: 'ac51', file: 'ac51.png' },
  { name: 'ac52', file: 'ac52.png' },
  { name: 'ac53', file: 'ac53.png' },
  { name: 'ac54', file: 'ac54.png' },
  { name: 'xhj001', file: 'xhj001.png' },
  { name: 'xhj002', file: 'xhj002.png' },
  { name: 'xhj003', file: 'xhj003.png' },
  { name: 'xhj004', file: 'xhj004.gif' },
  { name: 'xhj005', file: 'xhj005.jpeg' },
  { name: 'xhj006', file: 'xhj006.png' },
  { name: 'xhj007', file: 'xhj007.jpeg' },
  { name: 'xhj008', file: 'xhj008.gif' },
  { name: 'xhj09', file: 'xhj09.gif' },
  { name: 'xhj10', file: 'xhj10.gif' },
  { name: 'xhj11', file: 'xhj11.jpeg' },
  { name: 'xhj12', file: 'xhj12.gif' },
  { name: 'xhj13', file: 'xhj13.gif' },
  { name: 'xhj14', file: 'xhj14.gif' },
  { name: 'xhj15', file: 'xhj15.gif' },
  { name: 'xhj16', file: 'xhj16.gif' },
  { name: 'xhj17', file: 'xhj17.gif' },
  { name: 'xhj18', file: 'xhj18.gif' },
  { name: 'xhj19', file: 'xhj19.gif' },
  { name: 'xhj20', file: 'xhj20.gif' },
  { name: 'xhj21', file: 'xhj21.gif' },
  { name: 'xhj22', file: 'xhj22.png' },
  { name: 'xhj23', file: 'xhj23.gif' },
  { name: 'xhj24', file: 'xhj24.jpeg' },
  { name: 'xhj25', file: 'xhj25.jpeg' },
  { name: 'xhj26', file: 'xhj26.gif' },
  { name: 'xhj27', file: 'xhj27.gif' },
  { name: 'xhj28', file: 'xhj28.gif' },
  { name: 'xhj29', file: 'xhj29.gif' },
  { name: 'xhj30', file: 'xhj30.gif' },
  { name: 'xhj31', file: 'xhj31.png' },
  { name: 'xhj32', file: 'xhj32.jpeg' },
  { name: 'xhj33', file: 'xhj33.gif' },
  { name: 'xhj34', file: 'xhj34.gif' },
  { name: 'xhj35', file: 'xhj35.gif' },
  { name: 'xhj36', file: 'xhj36.gif' },
  { name: 'xhj37', file: 'xhj37.jpeg' },
  { name: 'xhj38', file: 'xhj38.gif' },
  { name: 'xhj39', file: 'xhj39.gif' },
  { name: 'xhj40', file: 'xhj40.gif' },
  { name: 'xhj41', file: 'xhj41.gif' },
  { name: 'xhj42', file: 'xhj42.gif' },
  { name: 'xhj43', file: 'xhj43.gif' },
  { name: 'xhj44', file: 'xhj44.gif' },
  { name: 'xhj45', file: 'xhj45.gif' },
  { name: 'xhj46', file: 'xhj46.gif' },
  { name: 'xhj47', file: 'xhj47.gif' },
  { name: 'xhj48', file: 'xhj48.png' },
  { name: 'xhj49', file: 'xhj49.gif' },
]

/** 表情包图片 URL */
export function stickerUrl(sticker: Sticker): string {
  return `/stickers/${sticker.file}`
}

/**
 * 常见 emoji 的中文别名,供表情面板搜索用。
 * 只覆盖用户最常搜的(笑/哭/赞/心/火/星等),冷门 emoji 不填,避免数据膨胀。
 * 搜索时:query 命中 别名 或 emoji 字符本身 或 所在分组名,即匹配。
 */
export const EMOJI_ALIASES: Record<string, string[]> = {
  '😀': ['微笑', '笑', '开心'],
  '😁': ['露齿笑', '笑', '开心'],
  '😂': ['笑哭', '笑', '哭', '哈哈'],
  '🤣': ['笑死', '笑哭', '哈哈'],
  '😊': ['微笑', '害羞', '笑'],
  '😇': ['天使', '微笑'],
  '😍': ['花痴', '喜欢', '爱心眼'],
  '😘': ['亲亲', '飞吻', '亲吻'],
  '😋': ['好吃', '馋'],
  '😜': ['调皮', '吐舌'],
  '🤪': ['搞怪', '疯狂'],
  '🤔': ['思考', '疑问', '想'],
  '😐': ['无语', '面无表情'],
  '😏': ['坏笑', '得意'],
  '😒': ['不高兴', '哼'],
  '🙄': ['翻白眼', '无语'],
  '😬': ['尴尬', '龇牙'],
  '😌': ['放松', '安心'],
  '😪': ['困', '犯困', '睡觉'],
  '😴': ['睡觉', '呼'],
  '😷': ['口罩', '生病'],
  '🤢': ['恶心', '想吐'],
  '🤮': ['呕吐', '吐'],
  '🥵': ['热', '大汗', '中暑'],
  '🥶': ['冷', '发抖'],
  '😎': ['酷', '墨镜'],
  '🤓': ['学霸', '眼镜', '书呆子'],
  '🥳': ['庆祝', '派对', '高兴'],
  '😭': ['大哭', '哭', '伤心'],
  '😤': ['气', '哼', '不服'],
  '😠': ['生气', '愤怒'],
  '😡': ['愤怒', '气炸', '红脸'],
  '🤯': ['震惊', '爆炸头'],
  '😱': ['惊吓', '尖叫'],
  '😨': ['害怕', '惊恐'],
  '😰': ['焦虑', '冷汗', '紧张'],
  '😥': ['担心', '松口气'],
  '😢': ['伤心', '难过', '哭'],
  '😣': ['痛苦', '纠结'],
  '😫': ['累', '疲惫', '崩溃'],
  '🥺': ['可怜', '委屈', '狗狗眼'],
  '😈': ['坏笑', '恶魔', '调皮'],
  '👿': ['生气', '恶魔'],
  '💀': ['骷髅', '死了', '笑死'],
  '☠️': ['骷髅', '危险'],
  '💩': ['大便', '屎', '便便'],
  '🤡': ['小丑', '丑角'],
  '👻': ['鬼', '幽灵'],
  '👽': ['外星人', 'UFO'],
  '🤖': ['机器人', 'AI'],
  '😺': ['猫', '微笑猫'],
  '👍': ['赞', '点赞', '好', '强', '加油'],
  '👎': ['踩', '差', '不好', '反对'],
  '👌': ['OK', '好的', '可以'],
  '✌️': ['耶', '胜利', '剪刀手'],
  '🤞': ['祈祷', '求', '好运'],
  '🤟': ['爱你', '手势'],
  '🤘': ['摇滚', '手势'],
  '👋': ['挥手', '拜拜', '再见', 'hello'],
  '🤝': ['握手', '合作'],
  '🙏': ['双手合十', '祈祷', '拜托', '感谢'],
  '✍️': ['写字', '签名'],
  '💪': ['肌肉', '加油', '健身'],
  '👀': ['眼睛', '看', '盯'],
  '👃': ['鼻子'],
  '👂': ['耳朵', '听'],
  '👄': ['嘴巴', '嘴唇'],
  '❤️': ['红心', '爱心', '喜欢', '爱'],
  '🧡': ['橙心', '爱'],
  '💛': ['黄心', '爱'],
  '💚': ['绿心', '爱'],
  '💙': ['蓝心', '爱'],
  '💜': ['紫心', '爱'],
  '🖤': ['黑心', '爱'],
  '💔': ['心碎', '伤心', '分手'],
  '💕': ['爱心', '喜欢'],
  '💖': ['爱心', '喜欢'],
  '💘': ['丘比特', '心动', '喜欢'],
  '💋': ['亲亲', '吻', '口红'],
  '💍': ['戒指', '钻戒', '求婚'],
  '💎': ['钻石', '宝石'],
  '✅': ['勾', '完成', '对', '通过'],
  '❌': ['叉', '错误', '不对', '取消'],
  '⭕': ['圈', '圆圈', '对'],
  '💯': ['满分', '一百分', '100'],
  '🔥': ['火', '火爆', '热门', '赞'],
  '⭐': ['星星', '星'],
  '🌟': ['星星', '闪耀', '亮'],
  '✨': ['星星', '闪光', '亮晶晶'],
  '⚡': ['闪电', '快', '电力'],
  '💫': ['晕', '转圈', '星'],
  '💥': ['爆炸', '碰撞'],
  '💢': ['生气', '怒', '火'],
  '💦': ['汗', '水滴', '流汗'],
  '💨': ['风', '跑', '烟'],
  '💬': ['对话', '说话', '气泡', '聊天'],
  '👥': ['多人', '群聊', '用户'],
  '💭': ['想法', '思考', '气泡'],
  '🎉': ['庆祝', '派对', '恭喜', '彩带'],
  '🎊': ['庆祝', '派对', '恭喜'],
  '🎁': ['礼物', '礼盒', '开箱'],
  '🎈': ['气球', '庆祝'],
  '🎀': ['蝴蝶结', '礼物', '可爱'],
  '🥰': ['开心', '喜欢', '幸福'],
}
